### ISSUE TITLE
Extension crashes

### ISSUE THREAD

**Issue by Moini** [nicolaromano/triangulate#1]
Traceback:
Traceback (most recent call last):
  File "triangulation.py", line 269, in <module>
    e.affect()
  File "/opt/inkscape0.92pre/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "triangulation.py", line 130, in effect
    self.doTriangulation(grp)
  File "triangulation.py", line 208, in doTriangulation
    pt, idx = kmeans2(np.array(coords), self.options.num_points, minit="points")
  File "/usr/lib/python2.7/dist-packages/scipy/cluster/vq.py", line 783, in kmeans2
    return _kmeans2(data, clusters, iter, nc, _valid_miss_meth[missing])
  File "/usr/lib/python2.7/dist-packages/scipy/cluster/vq.py", line 797, in _kmeans2
    new_code, has_members = _vq.update_cluster_means(data, label, nc)
  File "scipy/cluster/_vq.pyx", line 340, in scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4654)
TypeError: type other than float or double not supported

Inkscape 0.92pre on Linux Mint 18, tracing a linked photo.

**Comment by vmario89** [comment]
on a Windows system it seems that there need to be installed some additional modules to make it run. I dont get it working (Inkscape 0.92.4)

```
Traceback (most recent call last):
  File "triangulation.py", line 26, in <module>
    import inkex, urlparse, urllib, os, random, numpy, scipy, cv2
ImportError: No module named scipy
```


https://www.scipy.org/scipylib/download.html

**Comment by vmario89** [comment]
i got the same error now after i fixed some problem. At first i installed Python2.7 to C:\ and set custom python runtime in inkscape now by preferences.xml

the i installed some python modules
`pip install Image numpy scipyopencv-python`


i had to modify the Image module to "from PIL import Image"
> import inkex, urlparse, urllib, os, random
> from drawing_utils import draw_SVG_path, draw_SVG_rect
> from PIL import Image



The stack trace:

```
Traceback (most recent call last):
  File "triangulation.py", line 270, in <module>
    e.affect()
  File "C:\Users\mario\Seafile\cloud.leyghis.de\PortableApps\inkscape-0.92.4-x64\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "triangulation.py", line 131, in effect
    self.doTriangulation(grp)
  File "triangulation.py", line 209, in doTriangulation
    pt, idx = kmeans2(np.array(coords), self.options.num_points, minit="points")
  File "C:\Python27\lib\site-packages\scipy\cluster\vq.py", line 708, in kmeans2
    new_code_book, has_members = _vq.update_cluster_means(data, label, nc)
  File "_vq.pyx", line 342, in scipy.cluster._vq.update_cluster_means
TypeError: type other than float or double not supported


maybe the scipy module is too new or so
```

**Comment by nicolaromano** [comment]
Hi, @vmario89 and @Moini sorry for not coming back to you earlier.
Unfortunately, I am not maintaining this anymore (at least in the short term). Thank you for making me aware of the issue and giving a possible solution, maybe if I have time in the future I will consider updating it.

**Comment by vmario89** [comment]
https://github.com/nicolaromano/triangulate/pull/3
